version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    environment:  
      - DATABASE_HOST=8.138.123.250  
      - DATABASE_PORT=3306  
      - DATABASE_USER=robot  
      - DATABASE_PASSWORD=root123456  
      - DATABASE_NAME=robot 
    depends_on:
      - mysql-container
    networks:
      - common-network
  mysql-container:
    image: mysql:8.0  
    command: --default-authentication-plugin=mysql_native_password  
    restart: always  
    environment:  
      MYSQL_ROOT_PASSWORD: root123456  
    ports:  
      - "3306:3306"
networks:
  common-network:
    driver: bridge