version: '3.8'
services:
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - mysql-container
    networks:
      - common-network
  mysql-container:
    image: mysql  
    volumes:
      - /Users/guang/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: robot
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
networks:
  common-network:
    driver: bridge