version: '3.8'
services:
  fe-app:
    image: registry.cn-guangzhou.aliyuncs.com/robot_mobei/robot:001
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - 3005:3005
    depends_on:
      - mysql-container
    networks:
      - common-network
  mysql-container:
    image: mysql  
    ports:
      - 3306:3306
    volumes:
      - /Users/guang/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: robot
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      - common-network
networks:
  common-network:
    driver: bridge